version: '2'

services:

  jenkins:
    build: jenkins-with-docker
    container_name: jenkins
    ports:
      - 8888:8080
      - 50000:50000
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /etc/localtime:/etc/localtime:ro
      - /var/log:/var/log
      - /etc/docker/certs.d:/etc/docker/certs.d
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: "-Duser.timezone=Asia/Shanghai"

 