version: '2'

services:

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    ports:
      - 8889:8081
    volumes:
      - ./artifactory:/var/opt/jfrog/artifactory
      - /etc/localtime:/etc/localtime:ro
    environment:
      JAVA_OPTS: "-Duser.timezone=Asia/Shanghai"

